### ISSUE TITLE
Investigate Tailwind

### ISSUE THREAD

**Issue by bhanford9** [bhanford9/SkillJourney#1]
Currently the project is using a Component Library called MudBlazor. It has a lot of awesome features, but does not have a lot of UI independence. Using something like Tailwind would give us a lot of features as well, but also give us some customizability of things... this of course comes with the need to do some extra work to implement customized and uniform Components.

The goal of this would be to figure out what all is necessary to develop using Tailwind and what kind of tools it can provide:
- Theme Customizations?
- Dark/Light Mode toggle
- Dialog Service
- etc.

Documenting these things and breaking out some more Issues to handle implementing some of these things independently would would be a good outcome

**Comment by bhanford9** [comment]
@sterlingjhayden

**Comment by sterlingjhayden** [comment]
Theme customization is easy by directly adding styling classes or using Tailwind's @apply for a more reusable approach. There are dark mode "overrides" that can be applied alongside light mode styling, and Tailwind takes care of applying it appropriately. Dialog services are not included, but can be styled easily.

**Comment by sterlingjhayden** [comment]
Theme customization is easy by directly adding styling classes or using Tailwind's @apply for a more reusable approach. There are dark mode "overrides" that can be applied alongside light mode styling, and Tailwind takes care of applying it appropriately. Dialog services are not included, but can be styled easily.
